-- Dumps what tests/stock_buildings.lua needs from the running game (#159): every
-- stock village schematic in the layout tests/fixtures/church_voxelibre_0_92_3.lua
-- uses, and the definitions of the nodes they contain. Run by ../../run.sh on a
-- throwaway world; the files go to its fixtures/ directory (mod security keeps
-- mods from writing anywhere else) and run.sh copies them out.
local core = minetest
local out = core.get_worldpath() .. "/fixtures"
local version = core.settings:get("lv_extract_version") or "unknown"

-- Buildings VoxeLibre's village generator can place (mcl_villages/init.lua).
local BUILDINGS = {
	"belltower", "blacksmith", "butcher", "church", "farm", "lamp", "large_house",
	"library", "medium_house", "small_house", "tavern", "well",
}
-- Nodes the tests meet that are not in a stock schematic: what the furnishing
-- modules add, what the village generator swaps in (mcl_villages/buildings.lua),
-- and the stand-ins for terrain and for the outdoor targets the tests build.
local EXTRA_NODES = {
	"air", "ignore", "mcl_core:dirt", "mcl_core:dirt_with_grass", "mcl_core:grass_path",
	"mcl_core:stone", "mcl_core:sand", "mcl_core:water_source", "mcl_core:water_flowing",
	"mcl_villages:stonebrickcarved", "mcl_stairs:slab_wood",
	"mcl_decor:chair_wooden", "mcl_decor:table_wooden", "mcl_itemframes:plate",
	"mcl_jukebox:jukebox", "living_villages:pulpit", "mcl_lectern:lectern",
	"mcl_beds:bed_red_bottom", "mcl_beds:bed_red_top",
	"mcl_composters:composter", "mcl_cartography_table:cartography_table",
	"mcl_doors:wooden_door_b_1", "mcl_doors:wooden_door_t_1",
	"mcl_doors:wooden_door_b_2", "mcl_doors:wooden_door_t_2",
	"mcl_doors:wooden_door_b_3", "mcl_doors:wooden_door_t_3",
	"mcl_doors:wooden_door_b_4", "mcl_doors:wooden_door_t_4",
	"mcl_doors:iron_door_b_1", "mcl_doors:iron_door_t_1",
}
local NODE_FIELDS = {
	"walkable", "drawtype", "paramtype2", "collision_box", "node_box", "liquidtype",
	"damage_per_second", "buildable_to", "climbable",
}

local function quote(value)
	return string.format("%q", value)
end

-- A deterministic serializer for plain data: sorted keys, no functions.
local function serialize(value)
	local kind = type(value)
	if kind == "number" or kind == "boolean" then return tostring(value) end
	if kind == "string" then return quote(value) end
	if kind ~= "table" then return "nil" end
	local parts = {}
	if #value > 0 then
		for _, item in ipairs(value) do parts[#parts + 1] = serialize(item) end
		return "{" .. table.concat(parts, ", ") .. "}"
	end
	local keys = {}
	for key in pairs(value) do keys[#keys + 1] = key end
	table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)
	for _, key in ipairs(keys) do
		local label = type(key) == "string" and key:match("^[%a_][%w_]*$") and key or "[" .. serialize(key) .. "]"
		parts[#parts + 1] = label .. " = " .. serialize(value[key])
	end
	return "{" .. table.concat(parts, ", ") .. "}"
end

local function write(name, text)
	assert(core.safe_file_write(out .. "/" .. name, text), "could not write " .. name)
end

local function wrap_ids(ids)
	local lines = {}
	for first = 1, #ids, 26 do
		local row = {}
		for i = first, math.min(first + 25, #ids) do row[#row + 1] = ids[i] end
		lines[#lines + 1] = "\t\t" .. table.concat(row, ",") .. ","
	end
	return table.concat(lines, "\n")
end

local function extract_building(name, node_names)
	local path = core.get_modpath("mcl_villages") .. "/schematics/" .. name .. ".mts"
	local schematic = assert(core.read_schematic(path, {}), "cannot read " .. path)
	local handle = assert(io.open(path, "rb"))
	local bytes = handle:read("*a")
	handle:close()
	local size = schematic.size
	local names, index, ids, param2 = {}, {}, {}, {}
	for i = 1, size.x * size.y * size.z do
		local cell = schematic.data[i]
		if not index[cell.name] then
			names[#names + 1] = cell.name
			index[cell.name] = #names - 1
		end
		node_names[cell.name] = true
		ids[i], param2[i] = index[cell.name], cell.param2 or 0
	end
	local quoted = {}
	for _, node in ipairs(names) do quoted[#quoted + 1] = quote(node) end
	local text = string.format([[
-- The stock %s from VoxeLibre %s, as furnish() receives it: every cell of
-- mods/MAPGEN/mcl_villages/schematics/%s.mts (%d bytes, before the village generator's own
-- node swaps). Generated by tools/extract_schematics/run.sh; do not edit.
-- Cells are listed in schematic order (x fastest, then y, then z) as indexes
-- into names, with the cell's param2 alongside.
return {
	size = {x = %d, y = %d, z = %d},
	names = {%s},
	ids = {
%s
	},
	param2 = {
%s
	},
}
]], name, version, name, #bytes, size.x, size.y, size.z, table.concat(quoted, ", "),
		wrap_ids(ids), wrap_ids(param2))
	write(name .. ".lua", text)
	core.log("action", string.format("[lv_extract] %s: %dx%dx%d, %d nodes", name, size.x, size.y, size.z, #names))
end

local done = false
core.register_globalstep(function()
	if done then return end
	done = true
	core.mkdir(out)
	local node_names = {}
	for _, name in ipairs(BUILDINGS) do extract_building(name, node_names) end
	for _, name in ipairs(EXTRA_NODES) do node_names[name] = true end
	local sorted = {}
	for name in pairs(node_names) do sorted[#sorted + 1] = name end
	table.sort(sorted)
	local lines, missing = {}, {}
	for _, name in ipairs(sorted) do
		local def = core.registered_nodes[name]
		if def then
			local entry = {groups = def.groups or {}}
			for _, field in ipairs(NODE_FIELDS) do entry[field] = def[field] end
			lines[#lines + 1] = "\t[" .. quote(name) .. "] = " .. serialize(entry) .. ","
		else
			missing[#missing + 1] = name
		end
	end
	write("node_defs.lua", string.format([[
-- Definitions of the nodes in the stock village buildings and the furnishing around them,
-- from VoxeLibre %s with living_villages loaded. Generated by
-- tools/extract_schematics/run.sh; do not edit.
return {
%s
}
]], version, table.concat(lines, "\n")))
	if #missing > 0 then core.log("warning", "[lv_extract] not registered: " .. table.concat(missing, ", ")) end
	core.log("action", "[lv_extract] wrote " .. #sorted - #missing .. " node definitions to " .. out)
	core.request_shutdown()
end)
