-- The stock belltower from VoxeLibre 0.92.3, as furnish() receives it: every cell of
-- mods/MAPGEN/mcl_villages/schematics/belltower.mts (211 bytes, before the village generator's own
-- node swaps). Generated by tools/extract_schematics/run.sh; do not edit.
-- Cells are listed in schematic order (x fastest, then y, then z) as indexes
-- into names, with the cell's param2 alongside.
return {
	size = {x = 5, y = 6, z = 5},
	names = {"mcl_core:stonebrick", "air", "mcl_walls:stonebrick_0", "mcl_stairs:slab_wood", "mcl_stairs:slab_wood_top", "mcl_bells:bell", "mcl_lanterns:chain"},
	ids = {
		0,1,1,1,0,2,1,1,1,2,2,1,1,1,2,2,1,1,1,2,3,3,3,3,3,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,4,
		4,4,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,
		1,1,3,4,6,4,3,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,3,4,4,4,3,1,1,1,1,1,0,1,1,1,0,2,1,1,1,2,
		2,1,1,1,2,2,1,1,1,2,3,3,3,3,3,1,1,1,1,1,
	},
	param2 = {
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	},
}
