-- The stock lamp from VoxeLibre 0.92.3, as furnish() receives it: every cell of
-- mods/MAPGEN/mcl_villages/schematics/lamp.mts (176 bytes, before the village generator's own
-- node swaps). Generated by tools/extract_schematics/run.sh; do not edit.
-- Cells are listed in schematic order (x fastest, then y, then z) as indexes
-- into names, with the cell's param2 alongside.
return {
	size = {x = 3, y = 6, z = 4},
	names = {"mcl_core:dirt", "air", "mcl_doors:trapdoor_open", "mcl_fences:fence", "mcl_ocean:sea_lantern", "mcl_doors:trapdoor"},
	ids = {
		0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,
		1,1,1,1,1,2,1,1,1,1,0,0,0,1,3,1,1,3,1,1,3,1,2,4,2,1,
		5,1,0,0,0,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,
	},
	param2 = {
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,21,0,
		1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0,0,0,0,
	},
}
