name = villages
description = Villager lives, jobs, and taverns for VoxeLibre
depends = mobs_mc, mcl_beds, mcl_villages, mcl_decor, mcl_itemframes, mcl_cozy, mcl_jukebox
optional_depends = doc_identifier
