name = villages
description = Villager lives, jobs, and furnished taverns for VoxeLibre
depends = mobs_mc, mcl_beds, mcl_villages, mcl_decor, mcl_itemframes
optional_depends = doc_identifier, mcl_fishing
